name: clape
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - ld_impl_linux-64=2.40
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libnsl=2.0.1
  - libsqlite=3.46.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.1
  - pip=24.2
  - python=3.11.9
  - readline=8.2
  - setuptools=72.1.0
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.2.6
  - pip:
      - aiohappyeyeballs==2.3.5
      - aiohttp==3.10.3
      - aiosignal==1.3.1
      - attrs==24.2.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - filelock==3.15.4
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - huggingface-hub==0.24.5
      - idna==3.7
      - jinja2==3.1.4
      - lightning==2.4.0
      - lightning-utilities==0.11.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.3
      - numpy==2.0.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.1
      - pillow==10.4.0
      - pytorch-lightning==2.4.0
      - pyyaml==6.0.2
      - regex==2024.7.24
      - requests==2.32.3
      - safetensors==0.4.4
      - sympy==1.13.2
      - tokenizers==0.19.1
      - torch==2.4.0
      - torchaudio==2.4.0
      - torchmetrics==1.4.1
      - torchvision==0.19.0
      - tqdm==4.66.5
      - transformers==4.44.0
      - triton==3.0.0
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - yarl==1.9.4